name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: Output of the deployment
        value: ${{ jobs.deploy.outputs.outcome }}
      # secrets:
      #   some-secret:
      #     required: false
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Output Information
        run: echo "Deploy & Uploading.."
      - name: Set Result Output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
